@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "LoanBook Storage" #F4F6F6{
Class "<<interface>>\nLoanBookStorage" as LoanBookStorage
Class JsonLoanBookStorage
Class JsonSerializableLoanBook
Class JsonAdaptedLoan
Class JsonAdaptedTag
Class JsonAdaptedLoanTransaction
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" LoanBookStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> LoanBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonLoanBookStorage .up.|> LoanBookStorage
JsonLoanBookStorage ..> JsonSerializableLoanBook
JsonSerializableLoanBook --> "*" JsonAdaptedLoan
JsonAdaptedLoan --> "*" JsonAdaptedTag
JsonAdaptedLoan --> "*" JsonAdaptedLoanTransaction

@enduml
