@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedLoanBook" as VersionedLoanBook MODEL_COLOR
end box

[-> Model : undoLoanBook()
activate Model

Model -> VersionedLoanBook : undo()
activate VersionedLoanBook

VersionedLoanBook -> VersionedLoanBook :resetData(ReadOnlyLoanBook)
VersionedLoanBook --> Model :
deactivate VersionedLoanBook

[<-- Model
deactivate Model

@enduml
